---
title: "Physiological Analysis"
author: "XXX"
date: "2022-11-07"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(dplyr)
library(tidyr)
library(ggplot2)
library(stringr)
library(cowplot)
library(xlsx)
```

#Import Chla data for subsamples of colonies 
#Lab assays measured on 3 fragments/genotype in MMM-+6C treatments
Chicken : n=30
Pelorus East : n=20
```{r}
path="Data/"
chla=read.csv(paste0(path,"Aspath_chla.csv"),header=T)
```

#Regression between NDVI and Chlorophylle a 
```{r}
mplot= chla%>% ggplot(aes(x=1000*Chla_per_dw,y=MeanNDVI)) + geom_point(size=3,alpha=0.6)+ theme_linedraw()+ labs(x="Chlorophyll a (μg/g coral dry weight)",y="NDVI")+ theme(axis.text.x=element_text(size=20,color="black"),axis.text.y=element_text(size=20,color="black"),axis.title.x = element_text(size=18,color="black"),axis.title.y = element_text(size=20,color="black"),legend.title = element_text(size=15,color="black"),legend.text = element_text(size=20,color="black"),legend.position = "none",legend.background = element_rect(fill = "transparent"),
          panel.background = element_rect(colour = "black", size=1.5)) + 
  geom_smooth(method='lm', formula= y~x,size=1.5,colour="black")+
   ggpmisc::stat_poly_eq(formula =y~x, 
                aes(label = paste(..eq.label.., ..rr.label.., sep = "~~~")), 
                parse = TRUE,size=7)

log_plot=gphysio%>% ggplot(aes(x=log(1000*Chla_per_dw),y=MeanNDVI)) + geom_point(size=3,alpha=0.6)+ theme_linedraw()+ labs(x="log(Chlorophyll a (μg/g coral dry weight))",y="NDVI")+ theme(axis.text.x=element_text(size=20,color="black"),axis.text.y=element_text(size=20,color="black"),axis.title.x = element_text(size=18,color="black"),axis.title.y = element_text(size=20,color="black"),legend.title = element_text(size=15,color="black"),legend.text = element_text(size=20,color="black"),legend.position = "none",legend.background = element_rect(fill = "transparent"),
          panel.background = element_rect(colour = "black", size=1.5)) + 
  geom_smooth(method='lm', formula= y~x,size=1.5,colour="black")+
   ggpmisc::stat_poly_eq(formula =y~x, 
                aes(label = paste(..eq.label.., ..rr.label.., sep = "~~~")), 
                parse = TRUE,size=7)

#Same after aggregation at the genotype level 
mplot2= gphysio%>% group_by(Genotype,Treatment) %>% dplyr::summarise(Chla_per_dw=mean(Chla_per_dw),MeanNDVI=mean(MeanNDVI)) %>% ggplot(aes(x=1000*Chla_per_dw,y=MeanNDVI)) + geom_point(size=3,alpha=0.6)+ theme_linedraw()+ labs(x="Chlorophyll a (μg/g coral dry weight)",y="NDVI")+ theme(axis.text.x=element_text(size=20,color="black"),axis.text.y=element_text(size=20,color="black"),axis.title.x = element_text(size=18,color="black"),axis.title.y = element_text(size=20,color="black"),legend.title = element_text(size=15,color="black"),legend.text = element_text(size=20,color="black"),legend.position = "none",legend.background = element_rect(fill = "transparent"),
          panel.background = element_rect(colour = "black", size=1.5)) + 
  geom_smooth(method='lm', formula= y~x,size=1.5,colour="black")+
   ggpmisc::stat_poly_eq(formula =y~x, 
                aes(label = paste(..eq.label.., ..rr.label.., sep = "~~~")), 
                parse = TRUE,size=7)

log_plot2=gphysio %>% group_by(Genotype,Treatment) %>% dplyr::summarise(Chla_per_dw=mean(Chla_per_dw),MeanNDVI=mean(MeanNDVI)) %>% ggplot(aes(x=log(1000*Chla_per_dw),y=MeanNDVI)) + geom_point(size=3,alpha=0.6)+ theme_linedraw()+ labs(x="log(Chlorophyll a (μg/g coral dry weight))",y="NDVI")+ theme(axis.text.x=element_text(size=20,color="black"),axis.text.y=element_text(size=20,color="black"),axis.title.x = element_text(size=18,color="black"),axis.title.y = element_text(size=20,color="black"),legend.title = element_text(size=15,color="black"),legend.text = element_text(size=20,color="black"),legend.position = "none",legend.background = element_rect(fill = "transparent"),
          panel.background = element_rect(colour = "black", size=1.5)) + 
  geom_smooth(method='lm', formula= y~x,size=1.5,colour="black")+
   ggpmisc::stat_poly_eq(formula =y~x, 
                aes(label = paste(..eq.label.., ..rr.label.., sep = "~~~")), 
                parse = TRUE,size=7)

both_plot=ggdraw() + draw_plot(mplot,x=0,y=0.5,width=0.5,height=0.5) + draw_plot(log_plot,x=0.5,y=0.5,width=0.5,height=0.5) + draw_plot(mplot2,x=0,y=0,width=0.5,height=0.5) + draw_plot(log_plot2,x=0.5,y=0,width=0.5,height=0.5) + draw_plot_label(label=c("a", "b","c","d"),x=c(0.0, 0.50,0,0.5),c(1,1,0.5,0.5),size = 22)

ggsave(both_plot,filename=paste0("Figures/SupFigure_2.png"),width=12,height=8,dpi=320)
```
